In [149]:
import pandas as pd
import numpy as np

In [150]:
daily_sales = pd.read_csv("daily_sales.csv")
monthly_sales = pd.read_csv("monthly_sales.csv")

In [151]:
monthly_sales.head()

Month, Year    HM-NE   CF-NE   FF-NE    HM-SW   CF-SW   FF-SW    HM-NW  \
0      Jan-16  1140955  494802  285238  1124565  468568  281141  1111618   
1      Feb-16  1175529  489804  293882  1200559  480616  288369  1188037   
2      Mar-16  1235995  494802  296881  1220454  508522  293148  1151657   
3      Apr-16  1186592  514593  296648  1213616  485843  291505  1149180   
4      May-16  1272450  530187  305637  1249686  520702  312421  1187579   

    CF-NW   FF-NW    HM-SE   CF-SE   FF-SE     HM-C    CF-C    FF-C  
0  482079  277904  1095034  456264  273758  1126476  450958  281619  
1  475603  297009  1167009  486254  280311  1109076  462115  288586  
2  499443  287914  1133899  472458  295045  1167894  486622  280523  
3  498369  299021  1133767  491684  283441  1116560  465233  290533  
4  494824  296894  1215080  506283  291857  1155612  481505  300695

In [152]:
hm_col = [d for d in monthly_sales.columns if 'HM' in d]
monthly_sales['Year'] = pd.Series([s[-2:] for s in monthly_sales['Month, Year']]).astype(int)
monthly_sales['Month'] = (monthly_sales.index.values)%12 +1
df = monthly_sales.drop('Month, Year',axis =1)
df.head()

HM-NE   CF-NE   FF-NE    HM-SW   CF-SW   FF-SW    HM-NW   CF-NW   FF-NW  \
0  1140955  494802  285238  1124565  468568  281141  1111618  482079  277904   
1  1175529  489804  293882  1200559  480616  288369  1188037  475603  297009   
2  1235995  494802  296881  1220454  508522  293148  1151657  499443  287914   
3  1186592  514593  296648  1213616  485843  291505  1149180  498369  299021   
4  1272450  530187  305637  1249686  520702  312421  1187579  494824  296894   

     HM-SE   CF-SE   FF-SE     HM-C    CF-C    FF-C  Year  Month  
0  1095034  456264  273758  1126476  450958  281619    16      1  
1  1167009  486254  280311  1109076  462115  288586    16      2  
2  1133899  472458  295045  1167894  486622  280523    16      3  
3  1133767  491684  283441  1116560  465233  290533    16      4  
4  1215080  506283  291857  1155612  481505  300695    16      5

In [153]:
import matplotlib as plt

In [176]:
# monthly_sales.groupby('Year')[hm_col]
date = ['Year','Month']
hm_data = df.loc[:,hm_col+date]
# hm_data.groupby('Year').plot(x = 'Month', y = hm_col,title = 'Year')

In [180]:
np.array(hm_data[hm_col].mean(axis = 1))

array([1119729.6, 1168042. , 1181979.8, 1159943. , 1216081.4, 1211221.6,
       1232674.6, 1307492.6, 1276576.8, 1268773. , 1298048.8, 1268015.2,
       1337154.8, 1430596.4, 1363594.6, 1372741.4, 1392818.8, 1433511.6,
       1368166. , 1499575.2, 1470585.2, 1434058.2, 1509867.2, 1541555.2,
       1577552.6, 1598045.6, 1530862.4, 1589470.4, 1637278.6, 1525943. ,
       1602503.4, 1612050. , 1584584.2, 1356246.8, 1477280.4, 1390901.2,
       1513712.2, 1470051.2, 1453559.8, 1463568.2, 1524165.8, 1424835. ,
       1391288.2, 1438132. , 1428572. ])

In [185]:
cf_col = [d for d in monthly_sales.columns if "CF" in d]
cf_data = df.loc[:,cf_col+date]
# cf_data.groupby('Year').plot(x = 'Month', y = cf_col,title = 'Year')
np.array(cf_data[cf_col].mean(axis = 1))

array([470534.2, 478878.4, 492369.4, 491144.4, 506700.2, 500845.2,
       509465.4, 544738.8, 523572. , 532780.6, 549751.8, 519863.2,
       561625.6, 582289. , 577373.8, 562772.2, 575664.8, 592417.8,
       588853.8, 634612.4, 612692.4, 597458.2, 619249.2, 637234.4,
       646926.2, 665746.6, 627929. , 657012.4, 687679.6, 651350.4,
       667734.6, 693448.8, 665446. , 572404. , 610462.8, 574813.8,
       625684.6, 612312.8, 600709. , 614631.4, 635015. , 584353.2,
       570535.8, 599087. , 604753.4])

In [158]:
ff_col = [d for d in monthly_sales.columns if "FF" in d]
ff_data = df.loc[:,ff_col+date]
# ff_plot = ff_data.groupby('Year').plot(x = 'Month', y = ff_col,kind = 'scatter')

In [175]:
ff_mean = ff_data[ff_col].mean(axis = 1)
ff_data['agg'] = ff_mean
np.array(ff_mean)
# ff_plot = ff_data.groupby('Year').plot(x = 'Month', y = 'agg')

array([279932. , 289631.4, 290702.2, 292229.6, 301500.8, 302853.2,
       310621.4, 324180. , 321815.2, 322247. , 332376.6, 311917.6,
       339659. , 351988.4, 346453.4, 343184.8, 350913.2, 349704.8,
       350312.6, 377707.8, 361834.8, 361375.6, 377424. , 388435.2,
       385223.4, 405762. , 376668.6, 403892.2, 412607.8, 390810. ,
       397443.2, 402965.2, 399423.6, 346156.2, 372163.8, 342104. ,
       372350.2, 373325.4, 360596. , 371817.2, 378042.6, 350452.4,
       347771.8, 353771.4, 363005.2])

In [171]:
nw = [d for d in monthly_sales.columns if 'NW' in d]
nw_data = df.loc[:,nw].apply(lambda x: x.sum(),axis = 1)
np.array(nw_data)

array([1871601, 1960649, 1939014, 1946570, 1979297, 2033895, 2015714,
       2139988, 2124603, 2135427, 2162560, 2111721, 2248713, 2357234,
       2299477, 2237613, 2302404, 2389953, 2302992, 2561169, 2404606,
       2426288, 2517947, 2528700, 2629108, 2707575, 2553334, 2639394,
       2704249, 2615408, 2637788, 2754238, 2670893, 2288925, 2416298,
       2239571, 2557614, 2434056, 2419587, 2403681, 2553187, 2373539,
       2323544, 2399015, 2415468], dtype=int64)

In [196]:
np.array(nw_data.diff()[1:])/np.array(nw_data[:-1])

array([ 0.04757852, -0.01103461,  0.00389683,  0.01681265,  0.02758454,
       -0.00893901,  0.0616526 , -0.00718929,  0.0050946 ,  0.01270612,
       -0.02350871,  0.06487221,  0.04825916, -0.02450202, -0.02690351,
        0.02895541,  0.03802504, -0.03638607,  0.11210504, -0.06112951,
        0.00901686,  0.03777746,  0.00427054,  0.03970736,  0.02984548,
       -0.05696647,  0.03370495,  0.02457193, -0.03285237,  0.00855698,
        0.04414684, -0.03026064, -0.14301134,  0.05564752, -0.07313957,
        0.14201068, -0.04830987, -0.0059444 , -0.00657385,  0.06219877,
       -0.07036226, -0.02106348,  0.03248099,  0.00685823])

In [187]:
ne = [d for d in monthly_sales.columns if 'NE' in d]
ne_data = df.loc[:,ne].apply(lambda x: x.sum(),axis = 1)
np.array(ne_data)

array([1920995, 1959215, 2027678, 1997833, 2108274, 2091980, 2140709,
       2205580, 2153816, 2168676, 2234393, 2133837, 2301686, 2453707,
       2339264, 2359080, 2416127, 2465093, 2390742, 2537829, 2523511,
       2444177, 2621029, 2647775, 2640761, 2814604, 2609253, 2722007,
       2832936, 2641786, 2742490, 2786194, 2720638, 2320956, 2560458,
       2373509, 2593906, 2506324, 2507077, 2496457, 2645148, 2466669,
       2406800, 2465004, 2445513], dtype=int64)

In [197]:
np.array(ne_data.diff()[1:])/np.array(ne_data[:-1])

array([ 0.01989594,  0.0349441 , -0.01471881,  0.0552804 , -0.0077286 ,
        0.02329324,  0.03030351, -0.02346956,  0.00689938,  0.03030282,
       -0.04500372,  0.07866065,  0.06604767, -0.04664086,  0.00847104,
        0.02418188,  0.02026632, -0.03016154,  0.06152358, -0.00564183,
       -0.03143794,  0.07235646,  0.01020439, -0.00264902,  0.06583065,
       -0.07295911,  0.04321313,  0.04075265, -0.06747417,  0.03811967,
        0.01593588, -0.02352887, -0.14690745,  0.1031911 , -0.07301389,
        0.09285703, -0.03376452,  0.00030044, -0.00423601,  0.05956081,
       -0.06747411, -0.02427119,  0.02418315, -0.00790709])

In [188]:
sw = [d for d in monthly_sales.columns if 'SW' in d]
sw_data = df.loc[:,sw].apply(lambda x: x.sum(),axis = 1)
np.array(sw_data)

array([1874274, 1969544, 2022124, 1990964, 2082809, 2023180, 2095066,
       2250241, 2127713, 2170377, 2247531, 2143326, 2260916, 2419317,
       2300432, 2328692, 2339363, 2414319, 2357318, 2585228, 2462909,
       2429262, 2545089, 2592250, 2637128, 2662916, 2560765, 2676031,
       2804042, 2599733, 2688708, 2736147, 2710087, 2288687, 2526092,
       2352366, 2524880, 2537643, 2446863, 2540149, 2525821, 2350121,
       2322284, 2394712, 2424378], dtype=int64)

In [198]:
np.array(sw_data.diff()[1:])/np.array(sw_data[:-1])

array([ 0.05083035,  0.02669653, -0.01540954,  0.04613092, -0.02862913,
        0.03553119,  0.07406688, -0.05445106,  0.02005158,  0.03554866,
       -0.04636421,  0.05486333,  0.07006054, -0.0491399 ,  0.01228465,
        0.0045824 ,  0.0320412 , -0.02360956,  0.09668191, -0.04731459,
       -0.01366149,  0.04767991,  0.0185302 ,  0.01731237,  0.00977882,
       -0.03836058,  0.04501233,  0.04783614, -0.07286232,  0.03422467,
        0.01764379, -0.00952434, -0.15549316,  0.10372978, -0.06877263,
        0.07333638,  0.00505489, -0.03577335,  0.03812473, -0.00564061,
       -0.06956154, -0.01184492,  0.03118826,  0.01238813])

In [189]:
se = [d for d in monthly_sales.columns if 'SE' in d]
se_data = df.loc[:,se].apply(lambda x: x.sum(),axis = 1)
np.array(se_data)

array([1825056, 1933574, 1901402, 1908892, 2013220, 1997693, 1977396,
       2164116, 2131997, 2089130, 2130742, 2110360, 2216731, 2306213,
       2283604, 2242638, 2259342, 2330922, 2275408, 2451183, 2431953,
       2359954, 2413490, 2537451, 2577139, 2617479, 2500256, 2659690,
       2668593, 2485609, 2630319, 2666406, 2586340, 2223673, 2376833,
       2306116, 2491027, 2401803, 2384291, 2396331, 2475925, 2285149,
       2240780, 2348987, 2367390], dtype=int64)

In [199]:
np.array(se_data.diff()[1:])/np.array(se_data[:-1])

array([ 0.05946009, -0.01663862,  0.0039392 ,  0.05465369, -0.00771252,
       -0.01016022,  0.09442722, -0.01484163, -0.0201065 ,  0.01991834,
       -0.00956568,  0.0504042 ,  0.04036665, -0.00980352, -0.01793919,
        0.00744837,  0.03168179, -0.02381633,  0.07724988, -0.00784519,
       -0.02960542,  0.02268519,  0.05136172,  0.01564089,  0.01565302,
       -0.0447847 ,  0.06376707,  0.00334738, -0.06856947,  0.05821913,
        0.01371963, -0.03002769, -0.14022402,  0.06887703, -0.02975262,
        0.08018287, -0.03581816, -0.00729119,  0.00504972,  0.03321494,
       -0.07705241, -0.01941624,  0.04828988,  0.00783444])

In [190]:
c = [d for d in monthly_sales.columns if 'C' in d]
c_data = df.loc[:,c].apply(lambda x: x.sum(),axis = 1)
np.array(c_data)

array([3760766, 3792054, 3910264, 3862815, 3989808, 3953048, 4073519,
       4302509, 4187012, 4193066, 4358789, 4099118, 4434534, 4644358,
       4534279, 4482963, 4605064, 4656780, 4605283, 4976510, 4861845,
       4719382, 4940689, 5083633, 5154119, 5241503, 4998135, 5201127,
       5430773, 5115190, 5317999, 5397054, 5227325, 4567587, 4867205,
       4574719, 4921904, 4846080, 4723375, 4883257, 5035924, 4681058,
       4560349, 4752388, 4752802], dtype=int64)

In [200]:
np.array(c_data.diff()[1:])/np.array(c_data[:-1])

array([ 8.31958170e-03,  3.11730793e-02, -1.21344748e-02,  3.28757655e-02,
       -9.21347594e-03,  3.04754711e-02,  5.62142953e-02, -2.68441042e-02,
        1.44589984e-03,  3.95231079e-02, -5.95741157e-02,  8.18263831e-02,
        4.73159074e-02, -2.37016612e-02, -1.13173451e-02,  2.72366736e-02,
        1.12302457e-02, -1.10584996e-02,  8.06089441e-02, -2.30412478e-02,
       -2.93022505e-02,  4.68932161e-02,  2.89319971e-02,  1.38652810e-02,
        1.69542069e-02, -4.64309569e-02,  4.06135489e-02,  4.41531230e-02,
       -5.81101438e-02,  3.96483806e-02,  1.48655538e-02, -3.14484532e-02,
       -1.26209486e-01,  6.55965612e-02, -6.00932157e-02,  7.58920930e-02,
       -1.54054203e-02, -2.53204652e-02,  3.38491015e-02,  3.12633556e-02,
       -7.04669093e-02, -2.57866918e-02,  4.21105929e-02,  8.71140993e-05])

In [203]:
daily_sales.columns[2:]

Index(['HM-NE', 'CF-NE', 'FF-NE', 'HM-SW', 'CF-SW', 'FF-SW', 'HM-NW', 'CF-NW',
       'FF-NW', 'HM-SE', 'CF-SE', 'FF-SE', 'HM-C', 'CF-C', 'FF-C'],
      dtype='object')

In [220]:
np.array(daily_sales['FF-C'])

array([11232,  9152,  8406,  7940,  8607, 10228,  8993, 12463,  6799,
        7583,  9037,  8418,  9279,  7804, 11764,  9431,  7112,  9250,
        7773,  8276,  9376, 12847,  8713,  6881,  9227,  9194,  8185,
       10200, 12377,  7632,  7440], dtype=int64)

In [223]:
np.array(daily_sales.Day)

array(['1/1/2016', '1/2/2016', '1/3/2016', '1/4/2016', '1/5/2016',
       '1/6/2016', '1/7/2016', '1/8/2016', '1/9/2016', '1/10/2016',
       '1/11/2016', '1/12/2016', '1/13/2016', '1/14/2016', '1/15/2016',
       '1/16/2016', '1/17/2016', '1/18/2016', '1/19/2016', '1/20/2016',
       '1/21/2016', '1/22/2016', '1/23/2016', '1/24/2016', '1/25/2016',
       '1/26/2016', '1/27/2016', '1/28/2016', '1/29/2016', '1/30/2016',
       '1/31/2016'], dtype=object)

In [229]:
np.array(daily_sales[cf_col].mean(axis = 1))

array([15383. , 14555.8, 15431.4, 15257.8, 15012.4, 15103.2, 14987.6,
       14417.2, 14313.6, 15446.2, 15799. , 15444.2, 15516.2, 14945.2,
       15490.6, 15246.8, 15585.6, 14927.4, 14667.6, 14937.6, 15440.8,
       15708. , 14762.4, 14902. , 15650.8, 15296. , 15602.4, 15350.4,
       14900.4, 14982. , 15470.6])

In [236]:
np.array(daily_sales.iloc[:,0])

array(['Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday',
       'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
       'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
       'Sunday'], dtype=object)

In [259]:
np.array(daily_sales[ff_col].iloc[:,4])

array([11232,  9152,  8406,  7940,  8607, 10228,  8993, 12463,  6799,
        7583,  9037,  8418,  9279,  7804, 11764,  9431,  7112,  9250,
        7773,  8276,  9376, 12847,  8713,  6881,  9227,  9194,  8185,
       10200, 12377,  7632,  7440], dtype=int64)

In [254]:
daily_sales[ff_col]

FF-NE  FF-SW  FF-NW  FF-SE   FF-C
0    8446  10204   9924  11734  11232
1    7950   7316   9028   8005   9152
2    8397   8683   8105   7011   8406
3    9537   8429   8034   8201   7940
4   10123  10085   9879   8874   8607
5    8410   9652   9360   9674  10228
6   11791   8985   8834   8370   8993
7    8179  10985  10639  11630  12463
8    7193   7616   8589   6890   6799
9   10580   7105   7702   7520   7583
10  10091   9506   8566   9312   9037
11   9247   8424   8555   7735   8418
12  10250   9316   9872   8416   9279
13  12264   8832   8617   8826   7804
14   7127  10360  10503  11533  11764
15   7174   8140   8543   8346   9431
16   9313   7152   7177   7647   7112
17   8441   9602   9107   8793   9250
18   9101   8425   8765   8436   7773
19   8739   9944   9474   8426   8276
20  11108   9787   9876   8637   9376
21   6865  11615  10598  11709  12847
22   7271   9015   8058   8189   8713
23   9887   7722   7680   7167   6881
24   9068   9428   8892   8545   9227
25   9835   8632   7952   8565   9194
26  10656   9102   8609   8954   8185
27  12027   9959   9768   9376  10200
28   7554  10941  10364  12241  12377
29   7413   7877   8465   7727   7632
30  11201   8302   8369   7269   7440